magic method localeCompare :)
js-tasks-ru/js-20211109_daniil115 pull request #2
Opened 2021-11-14 21:46 UTC by dxndvndxn

2021-11-14 21:47 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-11-15 21:34 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2021-11-16 10:08 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return output.reverse()
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2021-11-16 10:08 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  for (let prop of fields) {
`const prop`

2021-11-16 10:08 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +    delete obj[prop]
использовать `delete` в связке с объектом не рекомендуется, ведь копирование объекта `{...obj}` делает `shallow copy` или другими словами неглубокую копию, поэтому удаление может привести к весьма неожиданным последствиям

2021-11-16 10:09 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2021-11-16 15:25 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-11-18 18:37 UTC, dosandk approved these changes
good 👍

2021-11-18 18:37 UTC, merged